manifest:
  projects:
    - name: zephyr
      revision: v3.2.0
      url: https://github.com/zephyrproject-rtos/zephyr
      import:
        name-allowlist:
          - cmsis
          - hal_nordic
    - name: golioth
      path: modules/lib/golioth
      revision: main
      url: https://github.com/golioth/golioth-zephyr-sdk.git
      import: west-external.yml